Uploading Unix translation Issue #138
programminghistorian/jekyll pull request #1028
Opened 2018-09-23 21:58 UTC by mariajoafana

Uploading translation of Unix lesson

2018-09-24 00:03 UTC, vgayolrs approved these changes

2018-09-24 11:36 UTC, mdlincoln requested changes
You can fix the broken links by making each of the links to other PH lessons start with `/es/lecciones/...` <- note the starting `/`

2018-09-25 02:57 UTC, vgayolrs submitted a review, later dismissed

2018-09-25 14:38 UTC, mariajoafana commented
Links are fixed, thanks @mdlincoln

2018-09-25 14:47 UTC, mdlincoln approved these changes

2018-09-25 14:47 UTC, mdlincoln commented
Thanks @mariajoafana - go ahead and merge when you're ready 🍾 🎊

2018-09-25 14:53 UTC, merged