Publishing corpus paralelo lfaligner
programminghistorian/jekyll pull request #1242
Opened 2019-03-27 03:45 UTC by mariajoafana

2019-03-27 04:02 UTC, mariajoafana commented
I'm waiting for the author's bio

2019-03-27 04:08 UTC, vgayolrs commented
Hola @mariajoafana Hay que incluir tópicos de la lección y la bio del autor para que Travis pueda pasar la confirmación.

2019-03-27 04:11 UTC, vgayolrs commented
El tópico tiene que estar en inglés: "distant-reading"

2019-03-27 04:12 UTC, vgayolrs requested changes
Cambiar en "topics" "lectura distante" por "distant-reading"

2019-03-27 08:00 UTC, arojascastro commented
Cool! Genial... por otra parte, ¿es realmente "lectura distante"? No sé, quizás necesitamos otro tópico para esta lección.

2019-03-27 13:09 UTC, mariajoafana commented
> Cool! Genial... por otra parte, ¿es realmente "lectura distante"? No sé, quizás necesitamos otro tópico para esta lección.

¿Será que "parallel corpus" o "paralell alignment" funcionan como tópicos?

2019-03-27 13:19 UTC, rivaquiroga commented
Quizás podría ser un tópico más general, como corpus "corpus building".

2019-03-27 16:21 UTC, vgayolrs commented
@mariajoafana @rivaquiroga @arojascastro : los tóplicos están pre-definidos:
<img width="775" alt="Captura de Pantalla 2019-03-27 a la(s) 10 20 30" src="https://user-images.githubusercontent.com/17665201/55093447-ff89da00-5079-11e9-8ade-0408d2e01615.png">

2019-03-27 16:22 UTC, arojascastro commented
Cierto, pero se pueden crear más, supongo. Pero, bueno, era solo una sugerencia, tampoco me parece super importante.

2019-03-27 16:27 UTC, vgayolrs commented
[aquí](https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/topics.yml) está la lista completa con traducción de los tópicos. Esa es la que habría que modificar para incluir el qu ese considere.

2019-03-27 17:29 UTC, mariajoafana commented
Ok, por el momento no propongamos otro tópico para este tutorial para que lo podamos publicar pronto, pero ya queda claro, gracias @vgayolrs qué tenemos que hacer para proponer uno nuevo

2019-03-28 00:07 UTC, vgayolrs submitted a review, later dismissed

2019-03-29 13:34 UTC, arojascastro submitted a review, later dismissed

2019-03-29 13:37 UTC, arojascastro commented
I don't know why this is not passing Travis. We get the following message:

1.44s$ _build/build.sh
Configuration file: /home/travis/build/programminghistorian/jekyll/_config.yml
            Source: /home/travis/build/programminghistorian/jekyll
       Destination: /home/travis/build/programminghistorian/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.7.4 | Error:  undefined method `each' for "distant-reading":String
The command "_build/build.sh" exited with 1.

I checked the YAML block and `distant-reading` is well written. Any idea @mdlincoln what's going on? Thank you.

2019-03-29 13:41 UTC, mdlincoln commented
Oh, I see - it's a tiny error but:

```
topics: distant-reading
```

in yaml is a one-to-one piece of data. `topics` is like `authors`, though - it can have one or _more_ values. So you need to write it like a list

```
topics: 
    - distant-reading
```

2019-03-29 13:46 UTC, arojascastro commented
Thank you @mdlincoln ! 

Now we got this error

* In /es/lecciones/corpus-paralelo-lfaligner.md:
  - [ ] 'Armando Luza' is not currently listed in ph_authors.yml. Check your spelling.
jekyll 3.7.4 | Error:  There were YAML errors.
The command "_build/build.sh" exited with 1.

2019-03-29 13:47 UTC, mdlincoln commented
check the spelling in `ph_authors.yml` 😆 it's slightly off

2019-03-29 13:47 UTC, arojascastro commented
Yup! Done 🥇

2019-03-29 13:52 UTC, arojascastro commented
Never ending:

 ./_site/es/lecciones/corpus-paralelo-lfaligner.html
  *  internally linking to "/"/es/lecciones/analisis-de-corpus-con-antconc, which does not exist (line 870)
     <a href="%22/%22/es/lecciones/analisis-de-corpus-con-antconc">AntConc</a>
htmlproofer 3.10.2 | Error:  HTML-Proofer found 1 failure!
The command "_build/build.sh" exited with 1.

2019-03-29 14:10 UTC, arojascastro commented
Yay 🎆

2019-03-29 14:36 UTC, mariajoafana commented
We need one more review and this will be ready to publish!

2019-03-29 14:38 UTC, mdlincoln requested changes

2019-03-29 14:38 UTC, mdlincoln commented on es/lecciones/corpus-paralelo-lfaligner.md
> +{% include figure.html filename="lfaligner-1.jpg" %}
This needs a caption

2019-03-29 14:38 UTC, mdlincoln commented on es/lecciones/corpus-paralelo-lfaligner.md
> +```
remove backticks around the jekyll figure code

2019-03-29 14:38 UTC, mdlincoln commented on es/lecciones/corpus-paralelo-lfaligner.md
> +```
remove backticks around the jekyll figure code

2019-03-29 14:38 UTC, mdlincoln commented on es/lecciones/corpus-paralelo-lfaligner.md
> +```
remove backticks around the jekyll figure code

2019-03-29 14:38 UTC, mdlincoln commented on es/lecciones/corpus-paralelo-lfaligner.md
> +```
remove backticks around the jekyll figure code

2019-03-29 14:38 UTC, mdlincoln commented on es/lecciones/corpus-paralelo-lfaligner.md
> +```
remove backticks around the jekyll figure code

2019-03-29 14:38 UTC, mdlincoln commented on es/lecciones/corpus-paralelo-lfaligner.md
> +También puedes [**descargar**](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/assets/corpus-paralelo-lfaligner/align_2018.08.03_14.09.46/DDHH_es-es-en-fr-pt.xls) el documento al
Please turn this into a relative link that points to `/assets/corpus-paralelo-lfaligner/...`

2019-03-29 14:38 UTC, mdlincoln commented on es/lecciones/corpus-paralelo-lfaligner.md
> +* Un texto de partida -digitalizado- y por lo menos una traducción de este. En este caso, alinearemos distintas traducciones de un documento que desde 1948 guía el quehacer y la convivencia humana en
Please turn these into relative links pointing to `/assets/corpus-paralelo-lfaligner...`

2019-03-29 14:39 UTC, mdlincoln commented
Also, everyone please make sure to look at the deploy preview: https://deploy-preview-1242--ph-dev.netlify.com/es/lecciones/corpus-paralelo-lfaligner and be satisfied that everything is displaying correctly.

2019-03-29 14:42 UTC, arojascastro commented
The abstract contains quotations marks that shouldn't be there and there are some images missing... i think

2019-03-29 17:16 UTC, mariajoafana reviewed
I just removed backticks and fixed relative links

2019-03-29 17:30 UTC, mariajoafana reviewed
fixed image link

2019-03-29 17:37 UTC, mariajoafana reviewed
fixed more broken links

2019-03-29 17:59 UTC, mariajoafana commented
Image 3a link needs fixing, my connection is failing, but will try again in the afternoon

2019-04-01 01:43 UTC, mariajoafana reviewed
fixed link for image 3a

2019-04-01 01:46 UTC, mariajoafana reviewed
fixed link to image 4a

2019-04-01 13:56 UTC, arojascastro submitted a review, later dismissed
cooooool

2019-04-01 14:41 UTC, mdlincoln approved these changes
publish whenever you're ready!

2019-04-01 16:49 UTC, merged