create welcome blogpost PH-FR in EN and FR, closes #1161 and #1184
programminghistorian/jekyll pull request #1264
Opened 2019-04-09 21:03 UTC by spapastamkou

I asked reviews from the @programminghistorian/english-team for the EN text and from the @programminghistorian/french-team for the FR text. 
Also, I have a small doubt about the image, that it might be too heavy. Do you think you can take a look, @mdlincoln and let me know if ok? It is [here](https://github.com/programminghistorian/jekyll/tree/welcome-ph-fr-blogposts/images/welcome-ph-fr). Thank you

2019-04-10 07:17 UTC, drjwbaker submitted a review, later dismissed
EN post is great. Thanks for this. If I was being picky, I'd lightly edit, but I think leaving as it is better captures the style I think you are going for in the FR original! On the image, do we have permission to republish it CC-BY? If not, we may want to mark the image as "© Mundaneum".

2019-04-10 07:28 UTC, mpuren requested changes
Thanks a lot for this blogpost, it is perfect. One minor correction in the french version : "mais aussi d'autres chercheur(e)s en sciences humaines et sociales" -> "mais aussi d'autres chercheur(se)s en sciences humaines et sociales"

2019-04-10 09:27 UTC, mpuren submitted a review, later dismissed

2019-04-10 09:28 UTC, spapastamkou commented
Thank you @drjwbaker and @mpuren. 
@drjwbaker, you may edit if you think the text will be better:)
@mpuren, I put chercheuses instead of chercheures and split to avoid parenthesis AND "s" in the middle:)

2019-04-10 14:26 UTC, mdlincoln commented
@spapastamkou Can you please reduce the image to maybe 800px width? That's the max size it will display on the site, that will reduce the file size a lot.

2019-04-12 13:13 UTC, mdlincoln requested changes

2019-04-12 13:13 UTC, mdlincoln commented on _posts/2019-08-04-bienvenue-ph-fr.md
> +<p><figure><img src="/images/welcome-ph-fr.png" /><figcaption>Schéma de Paul Otlet: documentation et télécommunication, <i>Mundaneum, Centre d'archives de la Fédération Wallonie-Bruxelles, Mons, Belg
You have a broken image link - this should be `images/welcome-ph-fr/welcome-ph-fr.png`

2019-04-12 13:53 UTC, mdlincoln approved these changes

2019-04-12 13:53 UTC, merged

2019-04-12 14:48 UTC, spapastamkou commented
oh my God! I just tweeted the EN version of the post and date appears as 4 August:( It was 4 April, I surely reversed the day and month in the format. Sorry. If I create a new branch and rename the files, will you hate me, @mdlincoln ?