convert Output Text as HTML to python3
programminghistorian/jekyll pull request #1514
Opened 2019-10-25 12:17 UTC by acrymble

Converts Output text as HTML lesson to python3
Add Frederik Elwert as reviewer
remove python2 warning

2019-10-28 00:11 UTC, svmelton requested changes
I can't see any issues at a glance, but it looks like some of the checks failed. I'm not able to tell what happened but wanted to flag the issue.

2019-10-28 16:26 UTC, mdlincoln commented
Yes @svmelton indeed, the checks found some issues. The instructions here: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status show how to check the problems that Travis found.

However, in this case, the problems are bigger - @acrymble why is this creating a new file? Instead of editing the existing one? The errors are caused because the lesson url is new and has no matching images

2019-10-28 16:34 UTC, acrymble commented
oops. typo  in  slug.

2019-10-30 17:28 UTC, svmelton approved these changes

2019-10-30 17:41 UTC, alsalin approved these changes

2019-11-04 14:28 UTC, merged