Add Institutional Partner Programme text
programminghistorian/jekyll pull request #1656
Opened 2020-01-31 16:08 UTC by drjwbaker

Add Institutional Partner Programme text.

Closes https://github.com/programminghistorian/jekyll/issues/1625

Required EN and FR translation: pinging @programminghistorian/french-team @programminghistorian/spanish-team 

@acrymble: what are your thoughts on dropping the sponsorship route and replacing it with this? Or should we have both? (it doesn't hurt I guess)

2020-02-03 19:39 UTC, spapastamkou commented
@drjwbaker I committed a draft for the FR translation, where: 
- I left a phrase untranslated because I am not sure to understand it and prefer it to be checked by a native francophone speaker, that is anyone else of the @programminghistorian/french-team 
- I changed proposed currencies to adapt them to the francophone countries: I kept the euro as main reference and then canadian dollars and swiss francs. You might want to check the amounts, @drjwbaker, and maybe modify them. I converted them online on the basis of the amount in euros. 
- Left a part in comment because the text in EN sends to a Supporters page, but this is actually a Supporters section in the Support Us page (I have section in the FR text).

2020-02-03 20:03 UTC, fdlaramee commented
@drjwbaker @spapastamkou I have translated the missing bit and fixed a couple of typos. The issue related to the link to the Support Us page/section is still outstanding.

2020-02-03 20:08 UTC, acrymble commented
@drjwbaker @spapastamkou interesting problem currencies raise. How can we best handle the international angle without the financial risk of pre-defining the cost in every currency? The value of currencies fluctuate A LOT.

2020-02-03 20:11 UTC, fdlaramee commented
@acrymble  @drjwbaker @spapastamkou The easiest way would be to give the base amount in pounds and add "or the equivalent in your currency of choice at the time of the sponsorship agreement" or something similar. Maybe not as welcoming but effective?

2020-02-04 11:30 UTC, spapastamkou commented
@fdlaramee thank you very much.

2020-02-04 11:53 UTC, drjwbaker commented
On currency, I borrowed from what other similar projects do, but accept the problem. Alternatively

- we peg at £1000 and £165
- suggest indicate alternatives in other currencies so people have a sense of what £1000 and £165 might mean to them
- promise to use exact conversion using https://www.xe.com/currencyconverter/ if/when an institution wants to pay us in non-GBP.

Thoughts?

2020-02-06 03:18 UTC, rivaquiroga commented
I’ll finish the Spanish translation by the end of the week.

2020-02-06 08:14 UTC, drjwbaker commented
> On currency, I borrowed from what other similar projects do, but accept the problem. Alternatively
> 
>     * we peg at £1000 and £165
> 
>     * suggest indicate alternatives in other currencies so people have a sense of what £1000 and £165 might mean to them
> 
>     * promise to use exact conversion using https://www.xe.com/currencyconverter/ if/when an institution wants to pay us in non-GBP.
> 
> 
> Thoughts?

@acrymble?

2020-02-06 08:28 UTC, acrymble commented
I'd be wary of making any promises. The bank / paypal / whatever medium will be doing the conversions on currency. We also don't have the mechanisms to accept money in other currencies, so everything will be converted on the way into our account.

It might be over-thinking it to worry about multiple currencies, and not giving enough credit to our audiences that they understand about conversions or the fact that some organizations are based elsewhere. Maybe we shouldn't worry about it, and just list GBP?

2020-02-06 08:33 UTC, drjwbaker commented
My only qualm about GBP only is that every other similar org I looked at had - at least - indicative figures in other major international currencies (usually, $ and €). My original estimates `£1,000 GBP ($1,300 USD / €1,100 EUR)` could be there as indicative values, no?

2020-02-06 08:34 UTC, acrymble commented
Sure. And revise every 6 months as appropriate? I grew up in a country that NEVER had its currency listed in those lists. And we always managed. It's people from countries used to seeing their prices in their own currency that are most likely to be taken aback.

2020-02-06 08:36 UTC, drjwbaker commented
The text says we will revise each January. Because it is an annual sub, that seems sensible to me (so, whenever in 2020 you become a member you pay the same amount, then you pay the 2021 amount - set in Jan - once your initial 12 months comes to an end)

2020-02-07 10:13 UTC, drjwbaker commented
@spapastamkou @fdlaramee I've made it clear that the alternative values listed are approximate. Does 'environs' work as a French translation? (I've made the change anyway, despite my un peu français).

2020-02-07 10:19 UTC, fdlaramee commented
@drjwbaker You would want to spell “environ” without an S in this case. Or replace with “approximativement”.

2020-02-07 10:22 UTC, drjwbaker commented
merci @fdlaramee!

2020-02-13 10:51 UTC, drjwbaker commented
Thanks @rivaquiroga!

2020-02-13 10:57 UTC, drjwbaker commented
@acrymble This should be good to go (I think I fixed the previous build fails) in EN, ES, and FR. Could you review please so that we can merge and launch?

@jenniferisasi When you have some time, can we plan a little comms around this?

2020-02-13 11:49 UTC, acrymble requested changes
There is a closing anchor tag visible on the preview, which needs to be looked at:

Send Email</a>

I'd also ask if the section following needs to stay, since this seems to trump that? The one about being an organizational supporter?

2020-02-13 12:20 UTC, drjwbaker commented
Fixed the trailing anchor.

2020-02-13 12:22 UTC, drjwbaker commented
@acrymble On..

> I'd also ask if the section following needs to stay, since this seems to trump that? The one about being an organizational supporter?

..I asked that at the top of the PR. My feeling is yes, though we have the text and can revive if we get an offer/enquiry that sits outside the IPP. Agreed?

2020-02-13 12:27 UTC, acrymble approved these changes

2020-02-13 12:27 UTC, acrymble commented
Thanks @drjwbaker for your work on this.

2020-02-13 12:37 UTC, merged