Update Guidelines
programminghistorian/jekyll pull request #1844
Opened 2020-07-10 18:34 UTC by walshbr

Closes #1795. Note that this will be a draft pull request for feedback from the technical team and MEs. It will not be finalized until after the Portuguese team has finalized their work, as this pull request affects files that they are currently translating. 

### Checklist

- [ ] Assign yourself in the "Assignees" menu
- [ ] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [ ] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

2020-07-10 18:40 UTC, walshbr commented
@programminghistorian/technical-team - can one of you take a look at the instructions here to make sure that I've updated correctly based on our new policy to have authors email in their submissions for the editors to then upload the materials to ph-submissions.

@svmelton - since we just tried this out with the English team, could you read the diff as well to make sure it makes sense? https://github.com/programminghistorian/jekyll/pull/1844/files.

Note again that this is meant to remain drafted until after the Portuguese team is done translating their materials. So won't ask for review and translation until that time. @acrymble - I assume that leaving edits in draft form like this still respects their need to have the documents frozen so they remain in synch while also allowing us to keep working. But let me know if that's not the case.

2020-07-11 14:28 UTC, acrymble commented
@walshbr if you're making changes the portuguese team might like the option of just doing it right the first time? Maybe send them a message and find out. Reducing overall effort is a good thing.

2020-07-11 14:36 UTC, DanielAlvesLABDH commented
We will open and edit one file at a time, from the list mentioned in #1818, so if you want we can leave this file to last and then incorporate the changes made

2020-07-11 18:20 UTC, walshbr commented
Yeah I agree @acrymble - I was thinking the same thing. the more I think about it, though, @DanielAlvesLABDH - I'm inclined to just hold this pull request for now until we get the Portuguese team entirely merged. It feels a little hairy to try to coordinate multiple versions and keep track of what files are in what working state. Even just trying to make sense of the plan in the abstract I am finding a little difficult. So I'll keep this drafted for now and we can touch base when PT is merged?

2020-07-11 18:25 UTC, DanielAlvesLABDH commented
Fine

2020-07-18 17:42 UTC, svmelton commented
Thanks, @walshbr—the diff looks good to me, whenever we're ready to move forward.

2020-12-04 16:17 UTC, walshbr commented
@programminghistorian/technical-team is going to review the language here before asking for translations.

2020-12-09 19:12 UTC, jenniferisasi requested changes
Maybe on author-guidelines on step 1 you don't need to say that the account gives permission to upload; I think that might be confusing since they are not supposed to upload anything themselves. Maybe just "grant access to use our repository during he peer-review process". What do you think?

2020-12-09 19:17 UTC, walshbr commented
@jenniferisasi I think under this system we would just be having the editors do the initial upload of new materials so they can do initial revisions to the metadata and syntax. But ultimately we want them to then start working from and revising that file, right? (we don't want the editor to have to continually get a new version and re-upload it for the authors). So maybe…

A clarifying note in step one as you say, clarifying that this first upload will be done by the editor. and then in step four or five noting that future revisions to the lesson should be done to the file on the ph submissions lesson itself. 

Does that seem to make sense to you as a process?

2020-12-09 19:20 UTC, jenniferisasi commented
> @jenniferisasi I think under this system we would just be having the editors do the initial upload of new materials so they can do initial revisions to the metadata and syntax. But ultimately we want them to then start working from and revising that file, right? (we don't want the editor to have to continually get a new version and re-upload it for the authors). So maybe…
> 
> A clarifying note in step one as you say, clarifying that this first upload will be done by the editor. and then in step four or five noting that future revisions to the lesson should be done to the file on the ph submissions lesson itself.
> 
> Does that seem to make sense to you as a process?

It does! Send file to editor, editor uploads, then edits happen through GitHub. As it reads right now, the user could think: "oh, so I need to upload it and the editor has to find the file name in the repo".

2020-12-09 20:33 UTC, walshbr commented
@jenniferisasi I made changes to reflect your suggestions if you want to modify/dismiss your review.

2020-12-09 20:48 UTC, jenniferisasi submitted a review, later dismissed

2020-12-09 20:54 UTC, walshbr commented
Just a note - I pinged the tech team on slack to make sure no one else had further comments before requesting translation.

2020-12-09 20:58 UTC, walshbr commented
OK @programminghistorian/french-team @programminghistorian/spanish-team and @programminghistorian/portuguese-team. This is ready to translate. There are two files in question - 

en/author-guidelines.md
en/editor-guidelines.md

The diff to show which lines were changed can be found here - https://github.com/programminghistorian/jekyll/pull/1844/files. By default it will show a side-by-side view of the old file version on the left and the new file version on the right, and it should automatically show only the pieces of the files that were edited. Let me know if you have questions!

2020-12-09 21:35 UTC, jenniferisasi commented
Working on the @programminghistorian/spanish-team version

2020-12-09 22:07 UTC, rivaquiroga commented
> Working on the @programminghistorian/spanish-team version

Thanks! The changes to the Author Guidelines were already made on this PR: https://github.com/programminghistorian/jekyll/pull/1771. But we need to check if any changes were introduced after we updated that file.

2020-12-09 22:16 UTC, jenniferisasi commented
> #1771

Oh! I forgot about that. So, yes, we have a couple of new change. Since this now involves me checking on 3 different files, I am going to save my translation and check it by the end of the week (can't do the 2 things now, translated and double check)

2020-12-11 15:55 UTC, spapastamkou commented
Just to let you know that I started working on this and in the FR case it involves 3 files: authors, editors and translators guidelines. I find considerable differences in the authors guidelines (up to now) so I make further changes.

2020-12-12 14:46 UTC, spapastamkou commented
Please @fdlaramee or @mariechristineb check changes in https://github.com/programminghistorian/jekyll/pull/1844/commits/24e7594e920ce1427d5a4b267ca902337b1ddc46 if able to

2020-12-12 15:17 UTC, DanielAlvesLABDH commented
Just to let you know that I updated the Portuguese files

2020-12-12 15:24 UTC, DanielAlvesLABDH approved these changes, later dismissed
Made the changes to the PT files

2020-12-13 17:37 UTC, mariechristineb reviewed
@spapastamkou I added comments to 24e7594

2020-12-13 17:37 UTC, mariechristineb commented on fr/consignes-auteurs.md
> +Une fois que votre leçon a été préparée en suivant les consignes données ci-dessus, nous vous conseillons de la faire relire et éventuellement d'apporter des corrections pour l'améliorer. Ainsi, l'év
je dirais "pourra se concentrer sur le fond, plutôt que sur la forme, afin de vous aider à [...]" (si ça ne s'éloigne pas trop de l'original)

2020-12-13 17:37 UTC, mariechristineb commented on fr/consignes-auteurs.md
> +L'évaluation par les pairs a lieu dans le cadre d'un [ticket](https://github.com/programminghistorian/ph-submissions/issues) Github qui prend ainsi la forme d'un forum de discussion ouverte. Merci de
"et qu'elle reste disponible"

2020-12-13 17:37 UTC, mariechristineb commented on fr/consignes-auteurs.md
> +2) Ensuite, votre rédacteur ou  rédactrice assigné(e) propose la leçon à l'évaluation formelle par les pairs. Cela implique l'invitation d'au moins deux évaluateurs ou évaluatrices externes, mais pot
je remplaçerais "guidance" par "des indications" ou "une ligne directrice"

2020-12-13 17:37 UTC, mariechristineb commented on fr/consignes-auteurs.md
> +Il serait utile de consulter nos [consignes aux évaluateurs et évaluatrices](/fr/consignes-evaluateurs) qui détaillent notre processus de révision et de publication.
Je dirais plutôt "Consultez nos [consignes aux évaluateurs et évaluatrices](/fr/consignes-evaluateurs) afin de vous familiariser avec notre processus de révision et de publication." (ou "si vous souhaitez vous familiariser")

2020-12-13 17:37 UTC, mariechristineb commented on fr/consignes-auteurs.md
> +Notre équipe de bénévoles fait de son possible pour se garantir l'évaluation rigoureuse, collégiale et efficace des auteur(e)s par les pairs. Toutefois, il peut y avoir des failles, c'est pourquoi no
"pour garantir" (sans le 'se')
"ou encore si vous considérez" 
j'enlèverais le 'enfin' et je remplacerais simplement par "ou pour quel autre souci que ce soit"
"afin que nous puissions"

2020-12-13 17:37 UTC, mariechristineb commented on fr/consignes-auteurs.md
> +Pour ce faire, vous avez plusieurs points d'entrée et sentez-vous libre de contacter la personne avec laquelle vous êtes le plus à l'aise:
"d'entrée - sentez-vous"

2020-12-13 17:37 UTC, mariechristineb commented on fr/consignes-auteurs.md
> +* notre médiatrice indépendante ([Dr Hélène Huet](mailto:hhuet@ufl.edu).
Ailleurs sur le site, on n'utilise pas les titres

2020-12-14 02:28 UTC, rivaquiroga commented
@jenniferisasi, el único cambio que faltaba en la guía para autores y la guía para traductores era el punto 5 de estas indicaciones. Lo demás ya lo habíamos traducido con Maria José (este PR estuvo un tiempo como draft, así que aprovechamos mientras tanto de incorporar estos cambios en #1771).
Ya incorporé en #1771 ese punto (y una frase extra que agregaron en el número 1), así que lo único que por parte del equipo de español faltaría en este PR es agregar esta nueva información a la Guía del Editor.

2020-12-20 08:34 UTC, spapastamkou commented on fr/consignes-auteurs.md
> +Une fois que votre leçon a été préparée en suivant les consignes données ci-dessus, nous vous conseillons de la faire relire et éventuellement d'apporter des corrections pour l'améliorer. Ainsi, l'év
j'ai tout intégré, merci pour la relecture.

2020-12-20 08:37 UTC, spapastamkou commented
In integrated @mariechristineb comments in the FR guidelines and updated the branch.

2021-01-05 14:48 UTC, walshbr commented
@jenniferisasi @DanielAlvesLABDH @spapastamkou - just a note that if the translations are finished to go ahead and give an approving review on the pull request so that I can merge. Thank you!

2021-01-05 15:08 UTC, DanielAlvesLABDH approved these changes, later dismissed
PT translations are ok

2021-01-05 15:25 UTC, spapastamkou submitted a review, later dismissed

2021-01-11 22:58 UTC, jenniferisasi commented
@walshbr I probably have the silliest question ever: If I work directly on the branch for this PR, it doesn't show me the latest file that Riva pushed today (guía para autores) onto which I want to make the changes asked for in this PR ... if we update this branch somehow, will the right file show?

2021-01-12 14:06 UTC, walshbr commented
It's not a silly question  - you have to re-merge the main branch into older branches when the main one changes. And there's no clear way to do that in the github interface that I've ever seen (@ZoeLeBlanc might know otherwise). I just did so, though, so you should see the latest files now.

2021-01-12 18:35 UTC, jenniferisasi commented
Ok, I think with my uploads this issue is ready to be closed (once we re-approve).

2021-01-12 18:48 UTC, walshbr commented
I think if you just approve @jenniferisasi I should be good to merge. Nothing has changed on the Fr or Pt sides that would require them to re-review.

2021-01-12 18:48 UTC, jenniferisasi approved these changes
approved!

2021-01-12 18:49 UTC, merged