Updating contact information on research page (bio), #1913
programminghistorian/jekyll pull request #2011
Opened 2021-01-31 18:45 UTC by JimmyMedeiros82

*add the reason for your pull request here*

### Checklist

- [ ] Assign yourself in the "Assignees" menu
- [ ] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [ ] Add the appropriate "Label"
- [ ] [Ensure the Travis CI checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing Travis errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Travis Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-travis-errors). Then contact the technical team if you need further help.*

2021-01-31 18:53 UTC, JimmyMedeiros82 commented on research.md
> +  status: volunteer
my bio

2021-02-01 10:46 UTC, DanielAlvesLABDH requested changes
Olá @JimmyMedeiros82 esta informação que você colocou nesse ficheiro deve ser colocada antes no ficheiro https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/ph_authors.yml, seguindo o modelo das informações que já lá estão para outros colegas. Veja, por exemplo, as informações da Joana Paulino.
As alterações neste ficheiro "research.md" devem ser ignoradas. A equipe técnica do PH irá depois ajudar reverter isto.
Para aquelas alterações em ph_authors comece por criar uma issue (https://github.com/programminghistorian/jekyll/issues) explicando o que vai fazer.
De seguida deve ir a https://github.com/programminghistorian/jekyll e no botão "gh-pages" criar um novo "branch" com o nome "issue-NÚMERO_DA_ISSUE".
A seguir é que acede a https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/ph_authors.yml, verifica que o "branch" criado está selecionado e escolhe a opção "edit this file" (pequeno lápis no lado direito).
Introduz os seus dados no final do documento e depois clica em "commit changes".
A seguir regressa a https://github.com/programminghistorian/jekyll e aí aparece a informação sobre a alteração feita e um botão "compare/create pull request".
Cria então o pull request, pede revisão de alguém da equipe técnica e da minha parte e aguarda.

2021-02-08 17:08 UTC, JoshuaGOB commented
Hi @walshbr this PR isn't needed since @JimmyMedeiros82 is doing the changes to ph_authors.yml in #2032 

Would it be appropriate to close with comment and not merge?

2021-02-08 17:51 UTC, walshbr commented
Yep that's right @JoshuaGOB - i'll click the button.

2021-02-08 17:51 UTC, closed without merging