Ipp middle band
programminghistorian/jekyll pull request #2073
Opened 2021-03-19 09:50 UTC by acrymble

Closes #1988 - Middle IPP band

Adds a £400 rate for middle income countries to the EN/ES/FR pages.

The PT pages need a total redoing so I will update them all at once when we've had a chance.

I need my language checked on FR and ES:

* Paises de alto ingreso | Paises de ingreso medio | países AOD
* Pays à revenu supérieur | Pays à revenu intermédiaire | Tarifs échelonnés pour les pays éligibles à l'APD

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [x] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [x] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [x] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [x] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

2021-03-19 12:13 UTC, rivaquiroga approved these changes, later dismissed

2021-03-20 07:54 UTC, spapastamkou requested changes
The numbers above thousand need to be written without comma and adding a space instead: 1,200 => 1 200. I will make the changes.

2021-03-20 08:15 UTC, spapastamkou commented
I followed the official terms for categorizing countries according to income as per [this list](https://www.oecd.org/fr/cad/financementpourledeveloppementdurable/normes-financement-developpement/Liste-des-beneficiaires-de-l-APD-etablie-par-le-CAD-2020.pdf) of the OECD. Please check if you are happy with the form @acrymble, I may have changed the link placement.

2021-03-20 08:16 UTC, spapastamkou approved these changes

2021-03-20 09:25 UTC, merged