Update ph_authors.yml
programminghistorian/jekyll pull request #2116
Opened 2021-04-28 14:04 UTC by datalogism

*add the reason for your pull request here*

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [x] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

2021-04-28 14:55 UTC, spapastamkou requested changes
Il est nécessaire de faire qqs modifs:
1) twitter: enlever guillemets et arobase 
2) sortname: mettre ton nom de famille plutôt que le prénom 
3) il faut ajouter aussi une brève bio comme dans l'exemple copié ci-dessous. Si besoin de faire traduire aux autres langues, on fera signe aux équipes concernées.  
bio:
    en: |
      Fred Gibbs is an assistant professor of history at the University of
      New Mexico.
    es: |
      Fred Gibbs es profesor de Historia en la Universidad de Nuevo México.
    fr: |
      Fred Gibbs est professeur d'histoire à l'Université du Nouveau-Mexique.
    pt: |
      Fred Gibbs é professor assistente de História na University of New Mexico.

2021-04-28 15:00 UTC, spapastamkou commented
@datalogism Pour faire simple, il vaut mieux qu'on garde un seul pull request pour tout. Je te propose de faire un commit ici avec ton avatar, utiliser donc pour ajouter la photo la branche `datalogism-patch-2` ; et on va fermer les deux autres puis supprimer les branches correspondantes. 
Sache que de tte manière le build ici va échouer, car il y a un problème avec un lien cassé dans une leçon EN, mais on fera le merge une fois que celui-ci aura été réglé par l'équipe EN. 
Si ce n'est pas clair, fais-moi signe.

2021-04-28 15:56 UTC, datalogism commented
@spapastamkou normalement c'est tout bon ! redit moi

2021-04-30 09:57 UTC, spapastamkou approved these changes

2021-04-30 10:23 UTC, spapastamkou requested changes
@datalogism 
- dans name: mettre le nom pas en majuscules (mais Ringwald) - désolée, je n'avais pas vu la première fois 
- dans bio: 
   a) la même chose que pour name (mettre "Ringwald" partout, pas en majuscules)
   b) je crois que le diplôme est Master 2, non? 
   c) il vaut mieux rester aux éléments factuels, c'est-à-dire les diplômes et l'affiliation. Il vaut mieux enlever donc après la virgule (parce que ce n'est pas un élément de bio, mais la poursuite d'un objectif); si ta situation change, on peut toujours mettre à jour par la suite.

2021-04-30 13:54 UTC, datalogism commented
Oups, voilà c'est rectifié !
Ok, j'ai fais la modif du coup. En espérant que je remodifie vite cette bio :)

2021-04-30 17:45 UTC, spapastamkou commented
@programminghistorian/portuguese-team @programminghistorian/spanish-team Can you please help us translate this bio in your respective language: 
"Célian Ringwald has a master’s degree in data science and a master's degree in digital humanities from Université Lyon 2"
You are welcome to drop it here in comment, we'll do the changes. Thank you!

2021-04-30 17:46 UTC, spapastamkou submitted a review, later dismissed

2021-04-30 18:01 UTC, acrymble commented
@spapastamkou I think the bio is only needed for authors. We don't display it anywhere for editors.

2021-04-30 18:17 UTC, spapastamkou commented
@acrymble ... and what you say is quite true, I realize only now, as almost all editors of all teams have their bio in. So we are good to go here:)

2021-04-30 18:24 UTC, rivaquiroga commented
@spapastamkou, I added the translation anyway; just in case is needed in the future

2021-05-03 07:03 UTC, spapastamkou commented
@rivaquiroga thank you!

2021-05-03 07:10 UTC, spapastamkou approved these changes

2021-05-03 07:12 UTC, merged