Project Team update - Remove Pimenta
programminghistorian/jekyll pull request #2247
Opened 2021-08-31 08:09 UTC by acrymble

Ricardo Pimenta's onboarding was halted half-way through. @rivaquiroga noticed we didn't revert that, so this pull request removes him from the project team.

I've also updated both @drjwbaker and @ZoeLeBlanc to their new affiliations. Can you both let me know if I've made any mistakes on that?

### Checklist

- [ ] Assign yourself in the "Assignees" menu
- [ ] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [ ] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

2021-08-31 12:11 UTC, rivaquiroga submitted a review, later dismissed

2021-08-31 12:29 UTC, drjwbaker requested changes
Line 342 should read:

> James Baker is Director of Digital Humanities at the University of Southampton

But thanks for making the other changes :) That was on my to-do list for today!

2021-08-31 12:34 UTC, acrymble commented
@drjwbaker on the title change, this actually only applies to your publications, not the project team page. So if we update this it makes it look like publications you wrote 5 years ago were written by the Director of Digital Humanities at Southampton. Is that the desired outcome?

2021-08-31 12:35 UTC, drjwbaker commented
Huh. I worked at the BL when they were published!

2021-08-31 12:40 UTC, acrymble commented
> Huh. I worked at the BL when they were published!

Yes every time we update your bio it updates that info. So do you want it to say Southampton?

2021-08-31 16:08 UTC, drjwbaker commented
I'd prefer that.

2021-08-31 16:12 UTC, acrymble commented
Can I please get translations for the following sentence:

James Baker is Director of Digital Humanities at the University of Southampton

@programminghistorian/spanish-team @programminghistorian/french-team @programminghistorian/portuguese-team

2021-08-31 16:15 UTC, nivaca commented
Spanish:

James Baker es el Director de Humanidades Digitales de la Universidad de Southampton.

2021-08-31 17:17 UTC, DanielAlvesLABDH commented
Português:
"James Baker é Diretor de Humanidades Digitais da University of Southampton"

2021-08-31 17:41 UTC, spapastamkou commented
French: James Baker est directeur des humanités numériques à l'Université de Southampton

2021-09-25 14:06 UTC, DanielAlvesLABDH commented
Hi @acrymble and @drjwbaker! Need some help with this? Is it something missing? I'm starting a new Editor onboarding and just want to be sure. Thanks!

2021-09-27 07:49 UTC, drjwbaker approved these changes

2021-09-27 07:49 UTC, drjwbaker commented
@DanielAlvesLABDH sorry, I missed that my review was required.

2021-09-27 07:54 UTC, merged

2021-09-27 07:55 UTC, DanielAlvesLABDH commented
Thanks!