publishing Shiny R lesson
programminghistorian/jekyll pull request #2708
Opened 2022-10-19 01:37 UTC by hawc2

@svmelton @yann-ryan do you two mind reviewing and approving this pull request to publish Yann's lesson on Shiny? Anisa is out on leave but I think I did everything necessary for the JISC banner and all the markdown should render right, but please do a thorough look through to verify the lesson looks good to go. Thanks!

### Checklist

- [ ] Assign yourself in the "Assignees" menu
- [ ] Assign at least one individual or team to "Reviewers"
  - [ ] if the text needs to be translated, assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing edtor in your PR. Please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines) when writing your PR description
- [ ] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

2022-10-19 01:40 UTC, hawc2 commented
@jenniferisasi also adding you here for review since you're working on a translation of this lesson

2022-10-19 02:04 UTC, svmelton commented on en/lessons/shiny-leaflet-newspaper-map-tutorial.md
> +Note that this lesson doesn't teach any coding in R, other than what's necessary to create the web application, nor does it cover publishing the finished application to the web. A basic knowledge of
The markdown in this banner isn't rendering 
<img width="756" alt="Screen Shot 2022-10-18 at 10 02 59 PM" src="https://user-images.githubusercontent.com/7232545/196580132-485750aa-187b-4a29-9514-2587decaed58.png">

2022-10-19 02:19 UTC, svmelton commented on en/lessons/shiny-leaflet-newspaper-map-tutorial.md
> +2. Make the app.R file.
Small issue, but all the numbers are rendering as "1"
<img width="757" alt="Screen Shot 2022-10-18 at 10 18 54 PM" src="https://user-images.githubusercontent.com/7232545/196581935-f28d1801-fcd1-4d11-8621-479b8396f6d9.png">

2022-10-19 02:22 UTC, svmelton commented on en/lessons/shiny-leaflet-newspaper-map-tutorial.md
> +2. Create the Server Element
Same issue as above re: numbering

2022-10-19 02:28 UTC, svmelton commented on en/lessons/shiny-leaflet-newspaper-map-tutorial.md
> +###  Draw Points using the Reactive Dataframe.
Delete the period

2022-10-19 02:32 UTC, svmelton requested changes
Most of the comments here are minor (one typo, a couple of issues with numbering) and one of the banners isn't displaying correctly—the markdown isn't rendering.

2022-10-19 23:33 UTC, hawc2 commented
Thanks for catching all these details @svmelton! @yann-ryan will next do a final look through and adjust these markdown issues

2022-10-20 08:03 UTC, yann-ryan approved these changes

2022-10-20 13:45 UTC, hawc2 commented
@svmelton this pull request should have the changes you asked for, can you take a look now and approve or let us know about further edits?

@jenniferisasi do you have a moment to look over this before we publish as well?

2022-10-20 14:27 UTC, jenniferisasi approved these changes
👍  It looks good to me! Congrats

2022-10-20 14:41 UTC, svmelton approved these changes

2022-10-20 14:42 UTC, svmelton commented
Looks great!

2022-10-20 18:09 UTC, hawc2 commented
Thanks all! I'm publishing the lesson now

2022-10-20 18:18 UTC, hawc2 commented
@svmelton @ZoeLeBlanc I'm perplexed by what happened here. This pull request was ready to go. I made the mistake of thinking I'd pressed Merge, but then Closed the ticket before finishing merging. 

When I reopened the ticket, the build process ran again, and now the htmlproofer is throwing an error over a missing link. I don't really get how this link suddenly became an issue. What do we do in this situation?

2022-10-20 19:04 UTC, jenniferisasi commented
Since I get all the emails... I can help. @hawc2 this is totally normal :) It simply caught a broken link on your second time, because it checks every link we have on the site every time we build a PR. So if that link broke right at the moment you closed the ticket, coincidentally, the build picked it. 

The link belongs to another lesson: introduction-to-populating-a-website-with-api-data.html 

What we usually do in this case: the editor itself tries to find an alternative and replace the link in this same PR. Sometimes we even delete the link completely if impossible to find a solution. 

Hope that helps. Bottomline: totally normal to happen.

2022-10-20 22:50 UTC, hawc2 commented
Great, thanks so much @jenniferisasi for explaining!

2022-10-21 12:05 UTC, hawc2 commented
@jenniferisasi in this case, the link throwing the html-error seems to work fine for me: https://www.europeana.eu/api/v2/thumbnail-by-url.json?uri=http%3A%2F%2Fuurl.kbr.be%2F1017835%2Fthumbs%2Fs&size=LARGE&type=IMAGE

If the website renders correctly, what am I supposed to do? This wouldn't be an easy image to replace as its integral to a substantial portion of the lesson it seems

2022-10-21 15:10 UTC, jenniferisasi commented
> @jenniferisasi in this case, the link throwing the html-error seems to work fine for me: https://www.europeana.eu/api/v2/thumbnail-by-url.json?uri=http%3A%2F%2Fuurl.kbr.be%2F1017835%2Fthumbs%2Fs&size=LARGE&type=IMAGE
> 
Mmm let's re-run the build; this has happened before too... the build will pick a link that is "broken" for a split second and re-running it "fixes" it all...

2022-10-21 15:51 UTC, hawc2 commented
ok strange, well looks like we're good to go!

2022-10-21 15:52 UTC, merged