Publicar Introdução aos Dados Abertos Conectados
programminghistorian/jekyll pull request #2759
Opened 2022-11-21 17:14 UTC by DanielAlvesLABDH

Publicar a tradução de "Introduction to the Principles of Linked Open Data"

### Checklist

- [ ] Assign yourself in the "Assignees" menu
- [ ] Assign at least one individual or team to "Reviewers"
- [ ] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

2022-11-21 17:17 UTC, DanielAlvesLABDH commented
Olá @ericbrasiln. Quando tiver disponibilidade, agradeço o seu olhar atento numa última revisão deste PR. Será a 33!!!

2022-11-21 17:43 UTC, DanielAlvesLABDH commented
@ericbrasiln and @anisa-hawes can you help identify the origin of the error in the build? I see that it is on the images, but can't figured out what is wrong :-(

2022-11-21 18:06 UTC, anisa-hawes commented
Hello @DanielAlvesLABDH. I think the problem was that the `original:` field was missing from the YAML. This means that the file doesn't include instructions for where to locate the image files.

I might also need to fix the broken link to <http://dilipad.history.ac.uk/> which is the project website for Digging Into Linked Parliamentary Data. Perhaps we could exchange it for a link to the paper's final report <https://repository.jisc.ac.uk/6544/1/DiLiPaD_final_report_1.pdf>. 

I have a strange feeling that I've come across this broken link before...

2022-11-21 18:13 UTC, DanielAlvesLABDH commented
Thank you @anisa-hawes, that was the problem. As for the link, I think your suggestion could be a good alternative.

2022-11-21 18:13 UTC, anisa-hawes commented
Ideally, I'd also like us to take the opportunity to add in descriptive alt-text in for each image. I would need your help (or @ericbrasiln's, if he has time?) to do this, because the alt-text will need to be written in Portuguese (obviously). I've collated some links to guidance for writing alt-text on our Wiki page: [Achieving Accessibility: Alt text, Colour, Contrast](https://github.com/programminghistorian/jekyll/wiki/Achieving-Accessibility%3A-Alt-text%2C-Colour%2C-Contrast)

Meanwhile, I can double-check the typesetting and add in perma.cc links where appropriate 🙂

2022-11-24 11:24 UTC, ericbrasiln requested changes
@DanielAlvesLABDH I've made some corrections, mostly orthographic, and indicated some wrong links. 

@anisa-hawes I guess all images has `alt=text` now.

2022-11-24 11:24 UTC, ericbrasiln commented on pt/licoes/introducao-dados-abertos-conectados.md
> +Se precisar aprender a como explorar LOD usando a linguagem de consulta [SPARQL](https://pt.wikipedia.org/wiki/SPARQL), recomenda-se a lição de Matthew Lincoln ['*Using SPARQL to access Linked Open D
corrigir 'razaão' para 'razão'

2022-11-24 11:24 UTC, ericbrasiln commented on pt/licoes/introducao-dados-abertos-conectados.md
> +Quando criamos URIs para as entidades descritas pelo projeto '[Tobias](http://www.history.ac.uk/projects/digital/tobias)' (em inglês), escolhemos uma estrutura do tipo URL e escolhemos utilizar o nos
O link para o projeto Tobias [http://www.history.ac.uk/projects/digital/tobias](http://www.history.ac.uk/projects/digital/tobias)não abre o que se espere, mas sim a página [https://www.history.ac.uk/research/digital-history](https://www.history.ac.uk/research/digital-history)

2022-11-24 11:24 UTC, ericbrasiln commented on pt/licoes/introducao-dados-abertos-conectados.md
> +Estamos a inventar exemplos simplesmente para fins de ilustração, mas se quiser ligar os seus dados a outros datasets na "nuvem de dados conectados" deve olhar para as convenções que são utilizadas n
corrigir 'hieráquica' para 'hierárquica'

2022-11-24 11:24 UTC, ericbrasiln commented on pt/licoes/introducao-dados-abertos-conectados.md
> +Vamos realizar as nossas consultas SPARQL na [DBpedia](https://www.dbpedia.org/), que é um enorme conjunto de LOD derivado da Wikipedia. Além de estar cheio de informação que é muito difícil de encon
corrigir 'extremindade' para 'extremidade'

2022-11-24 11:24 UTC, ericbrasiln commented on pt/licoes/introducao-dados-abertos-conectados.md
> +Gostaria de agradecer aos meus dois colegas revisores, Matthew Lincoln e Terhi Nurmikko-Fuller e ao meu editor, Adam Crymble, por me ajudarem generosamente a melhorar esta lição com numerosas sugestõ
Mesmo coisa do meu comentário da linha 144.

2022-11-24 11:29 UTC, DanielAlvesLABDH commented on pt/licoes/introducao-dados-abertos-conectados.md
> +Quando criamos URIs para as entidades descritas pelo projeto '[Tobias](http://www.history.ac.uk/projects/digital/tobias)' (em inglês), escolhemos uma estrutura do tipo URL e escolhemos utilizar o nos
@anisa-hawes do you think we can change that link for this one: https://blog.history.ac.uk/2015/10/representing-tobias-our-new-ahrc-funded-project-building-on-the-bibliography-of-british-and-irish-history/

2022-11-24 11:32 UTC, DanielAlvesLABDH commented
Thank you @ericbrasiln. The one thing that it's missing is to correct the link for the Tobias project. Let's see what @anisa-hawes says...

2022-11-24 11:33 UTC, anisa-hawes commented on pt/licoes/introducao-dados-abertos-conectados.md
> +Quando criamos URIs para as entidades descritas pelo projeto '[Tobias](http://www.history.ac.uk/projects/digital/tobias)' (em inglês), escolhemos uma estrutura do tipo URL e escolhemos utilizar o nos
Perhaps we could replace the link on l.144 with this one: <https://gtr.ukri.org/projects?ref=AH%2FN003446%2F1#/tabOverview> which provides an overview of the Tobias Project. I can't locate the relevant page on IHR's website...

2022-11-24 11:34 UTC, anisa-hawes commented
Thank you @ericbrasiln and @DanielAlvesLABDH. Perhaps we could replace the link on l.144 with this one: <https://gtr.ukri.org/projects?ref=AH%2FN003446%2F1#/tabOverview> which provides an overview of the Tobias Project. 

I can't locate the relevant page on IHR's website...

2022-11-24 11:35 UTC, DanielAlvesLABDH commented on pt/licoes/introducao-dados-abertos-conectados.md
> +Quando criamos URIs para as entidades descritas pelo projeto '[Tobias](http://www.history.ac.uk/projects/digital/tobias)' (em inglês), escolhemos uma estrutura do tipo URL e escolhemos utilizar o nos
I agree. Will replace the link in the file

2022-11-24 11:44 UTC, DanielAlvesLABDH commented
No worries @anisa-hawes. Thanks for the help. I think we can make that change latter. @ericbrasiln all your suggested changes are introduced. I think we can close this. Thanks

2022-11-24 11:46 UTC, ericbrasiln approved these changes

2022-11-24 11:53 UTC, merged

2022-11-24 17:39 UTC, DanielAlvesLABDH commented
@anisa-hawes the PR went well, we closed it about 6 hours ago, but the lesson still doesn't show on the live site. What could have happen?

2022-11-25 12:05 UTC, anisa-hawes commented
Dear @DanielAlvesLABDH. 

I think an update may be required in our build workflow, so I have opened an Issue #2761 to investigate.

In this case, I've been able to re-run the job, and [it has merged in successfully](https://programminghistorian.org/pt/licoes/introducao-dados-abertos-conectados) 😄 

Making a note here to let @GeeAlmeida know that the doi for this new lesson isn't live yet, but will be soon so we can celebrate on Twitter later!

2022-11-25 12:21 UTC, DanielAlvesLABDH commented
Many thanks @anisa-hawes. It worked. Ita now live. 33!