Publicar Manipulação e transformação de dados com R
programminghistorian/jekyll pull request #2765
Opened 2022-11-28 11:36 UTC by DanielAlvesLABDH

Publicar a tradução da lição "Data Wrangling and Management in R"

### Checklist

- [ ] Assign yourself in the "Assignees" menu
- [ ] Assign at least one individual or team to "Reviewers"
- [ ] Add the appropriate "Label"
- [ ] [Ensure the status checks pass](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#4-check-your-pr-status)
- [ ] [Check the live preview of your PR on Netlify](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#5-preview-how-your-pr-looks-when-built-into-html)
- [ ] If this PR closes an open issue, add the phrase `Closes #ISSUENUMBER` to the description above

*If you are having difficulty fixing build errors, first consult <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions> carefully, especially ["Common Build Errors"](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions#common-build-errors). Then contact the technical team if you need further help.*

2022-11-29 22:03 UTC, ericbrasiln requested changes
Fiz a revisão da lição e executei o código.
Há apenas um pequeno erro de ortografia, que indiquei.

2022-11-29 22:03 UTC, ericbrasiln commented on pt/licoes/manipulacao-transformacao-dados-R.md
> +Nota da tradução: o conteúdo da programação utilizado na lição original foi alterado para esta versão em português para que o contexto e os exemplos sejam próximos da realidade da comunidade que fala
corrigir "No entando" para "No entanto".

2022-11-30 06:17 UTC, DanielAlvesLABDH commented on pt/licoes/manipulacao-transformacao-dados-R.md
> +Nota da tradução: o conteúdo da programação utilizado na lição original foi alterado para esta versão em português para que o contexto e os exemplos sejam próximos da realidade da comunidade que fala
Feito. Obrigado

2022-11-30 09:45 UTC, ericbrasiln approved these changes
Pronto!

2022-11-30 10:31 UTC, merged