Publish du html a une liste de mots (partie 1)
programminghistorian/jekyll pull request #3020
Opened 2023-09-06 14:02 UTC by marie-flesch

I am publishing the lesson "Du HTML à une liste de mots (partie 1)

2023-09-07 18:47 UTC, spapastamkou requested changes
faudrait peut-être descendre le niveau des titres de 1 à chaque fois: les titres niveau 1 => niveau 2 et ceux de niveau 2 => niveau 3 (pour harmoniser avec les autres versions de la leçon en EN, PT et ES). Sinon cela a l'air top!

2023-09-08 05:17 UTC, marie-flesch commented
> faudrait peut-être descendre le niveau des titres de 1 à chaque fois: les titres niveau 1 => niveau 2 et ceux de niveau 2 => niveau 3 (pour harmoniser avec les autres versions de la leçon en EN, PT et ES). Sinon cela a l'air top!

Bien vu, merci ! Oui on va faire ça. En fait finalement il y a d'autres changements à apporter, pour qu'il y ait une cohérence entre la partie 1 et la partie 2 (qui est en cours d'évaluation). Célian (le traducteur) s'en occupe la semaine prochaine !

2023-09-12 15:45 UTC, datalogism commented
Hello @marie-flesch  c'est tout bon pour moi :)
Bien repris ton commentaire @spapastamkou, j'ai aussi corrigé cela sur la partie 2 !

2023-09-14 12:54 UTC, anisa-hawes approved these changes

2023-09-14 12:56 UTC, anisa-hawes commented
Hello @marie-flesch. I've integrated Célian's most recent edits https://github.com/programminghistorian/ph-submissions/commit/bbc78e94f3ea23ddb150a55fa345f944faf79a60 and brought this branch up-to-date with gh-pages. 

I'm unclear about how to mark the changes requested by Sofia as resolved so that we can merge... I'll investigate, and update you as soon as possible.

2023-09-14 13:34 UTC, marie-flesch commented
Thank you so much @anisa-hawes, it looks good!

2023-09-14 15:07 UTC, spapastamkou approved these changes

2023-09-14 15:10 UTC, spapastamkou commented
@anisa-hawes resolved :-) - thanks!

2023-09-14 15:16 UTC, merged