Issue 3039
programminghistorian/jekyll pull request #3040
Opened 2023-10-05 16:38 UTC by anisa-hawes

I'm moving former (non-renewing) IPPs to the [Additional Supporters section](https://programminghistorian.org/en/supporters#additional-supporters) of our /en/supporters, /es/colaboradores, /fr/nos-soutiens, /pt/apoiadores pages.

Closes #3039 

### Checklist

- [x] Assign yourself in the "Assignees" menu
- [x] Add the appropriate "Label"
- [x] If this PR closes an Issue, add the phrase `Closes #ISSUENUMBER` to your summary above
- [ ] Ensure the status checks pass: if you have difficulty fixing build errors, please contact our Publishing Assistant @anisa-hawes 
- [ ] Check the Netlify Preview: navigate to netlify/ph-preview/deploy-preview and click 'details' (at right)
- [ ] Assign at least one individual or team to "Reviewers"
  - ~~[ ] if the text needs to be translated, please follow the [translation request guidelines](https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines), then assign the relevant language team(s) as "Reviewers" and tag both the team as well as the managing editor in your PR.~~

2023-10-12 14:42 UTC, anisa-hawes commented
Hello @charlottejmc,

When you have time, may I ask for your help to check my French on the following page?:
[ph-preview.netlify.app/fr/nos-soutiens](https://deploy-preview-3040--ph-preview.netlify.app/fr/nos-soutiens).

What I've done is: 

- Added a new heading Alumni Partners (_Partenaires des anciens élèves_) 
- Added a description to mean roughly Former contributors to our Institutional Partner Programme (_Les institutions suivantes ont participé de notre programme de Partenariat institutionnel_). Does this sound right?
- Added two sub-headings under Additional Supporters (_Soutien additionnel_) which I'd like to read the equivalent of Active and Past. Would _Actifs_ and _Passé_ seem right?

Thank you 🙂 

I've sub-divided Additional Supporters into active and past

2023-10-13 07:57 UTC, charlottejmc commented
Hi @anisa-hawes,

I have had a look and here are my thoughts:

- _Partenaires des anciens élèves_ sounds more like _Partners of alumni_. I am thinking _Anciens élèves partenaires_ instead – but this is a tricky phrase to translate.
- This is nearly right: _Les institutions suivantes ont participé **à** notre programme de Partenariat institutionnel_ is the only correction I can see!
- I think this could work as it is, although _Passé_ would just need to be in the plural form: _Passés_. However, I might suggest something along the lines of _En cours_ and _ Révolus_, which could sound more natural? Again, I feel like these are tricky phrases to translate directly.

I hope this helps!

2023-10-13 08:50 UTC, spapastamkou commented
hi, if I may, for the term "alumni partners", simply "anciens partenaires" ou "partenariats révolus" (as Charlotte proposes) can work here. (as élèves refers to students, and I believe is embarked from the auto translation of the initial alumni term)

2023-10-13 21:29 UTC, anisa-hawes commented
Hello @DanielAlvesLABDH,

I hope you're well. This PR represents some adjustments to the headings and sub-headings on our Supporters pages. Our aim is to create meaningful sub-headings within our lists of IPP, so we make clear who our active supporters are while also acknowledging institutions that have supported us in the past. May I ask for your help to adjust my attempted Portuguese translations?

- I added a new heading Alumni Partners (Parceiros ex-alunos? or Antigos parceiros?)
- I added a description to mean roughly Former contributors to our Institutional Partner Programme (Antigos contribuintes para o nosso Programa de Parceria Institucional)
- I added two sub-headings under Additional Supporters (Soutien additionnel) which I'd like to read the equivalent of Active and Past. Would Ativo and Anterior be appropriate?

You can [review the detail of my edits here](https://github.com/programminghistorian/jekyll/pull/3040/files). 

With thanks! Anisa

2023-10-13 21:34 UTC, DanielAlvesLABDH commented
Hi @anisa-hawes, will look at this tomorrow morning. Best

2023-10-14 08:37 UTC, DanielAlvesLABDH commented on pt/apoiadores.md
> +## Parceiros ex-alunos
Anteriores parceiros

2023-10-14 08:37 UTC, DanielAlvesLABDH commented on pt/apoiadores.md
> +## Apoiadores adicionais
Parceiros adicionais

2023-10-14 08:40 UTC, DanielAlvesLABDH requested changes
Have made some suggestions of change

2023-10-18 09:16 UTC, anisa-hawes commented
Hello @spapastamkou and @rivaquiroga 

This PR is ready, with each of the translations checked by native speakers. 

The only further change I've made is to update the information about which month we reset partnership rates. As discussed with @drjwbaker and @spapastamkou, going forwards will be reviewing our rates mid-year for reset in October (rather than January) to align with ProgHist Ltd's financial year. 

Thank you.

2023-10-18 09:36 UTC, rivaquiroga approved these changes

2023-10-18 10:14 UTC, DanielAlvesLABDH approved these changes

2023-10-18 10:14 UTC, merged