Update editorial guidelines refs #571
programminghistorian/jekyll pull request #573
Opened 2017-08-23 14:21 UTC by walshbr

Update the editorial guidelines for adding authors to the ph-authors.yml file a la #571. Syntax seemed out of date given the examples that are currently in there - I think it was referencing older syntax from before the website redesign and Spanish translations. Flagging @arojascastro to update the Spanish guidelines accordingly and @mdlincoln just to make sure I'm on track here.

2017-08-23 14:52 UTC, vgayolrs commented
@walshbr , I take this

2017-08-23 15:07 UTC, vgayolrs reviewed
@walshbr In principle, I agree with your proposal. But there are also entries of authors with other metadata that I do not know if it is convenient to include in the editor's guide (in case we have this data):
```
- name: Jonathan Reeve
  url: "http://jonreeve.com"
  twitter: j0_0n
  github: JonathanReeve
  team: false
  bio:
    en: |
        Jonathan Reeve is a digital humanist and web developer for the Modern Language Association.
```
@mdlincoln , what do you think?

2017-08-23 19:06 UTC, walshbr commented
@vgayolrs Was wondering myself about that. My sense was that the extra metadata you've identified there was only used for those of us on the project team, so it might be alright to leave out of the template. But open to other opinions.

2017-08-23 19:11 UTC, mdlincoln requested changes
It's not necessary to explicitly state `team: false`, as Liquid parses the lack of a `team` key as `team: false` by default.

2017-08-23 19:13 UTC, mdlincoln commented
And yes, the additional metadata on some author entries is only used for displaying editorial team status - so it certainly doesn't need to be added.. If `team: false` was the only change, then I think... this PR doesn't need to be merged?

2017-08-23 19:15 UTC, walshbr commented
Cool. @mdlincoln the only other bit I added was "en" where it wasn't already there - is the metadata also parsing as English by default?

2017-08-23 19:36 UTC, vgayolrs commented
Thanks for the explanation, @mdlincoln . So, it remains the same.

2017-08-23 20:37 UTC, mdlincoln commented
@walshbr oh crap, how did I miss that addition? Yes, it _does_ need the `en` subkey.

2017-08-23 20:37 UTC, mdlincoln submitted a review, later dismissed

2017-08-23 20:37 UTC, mdlincoln commented on editor-guidelines.md
> +  team: false
Remove this line only. Rest is good.

2017-08-23 22:03 UTC, walshbr commented
Cool! Should be good to merge now - just needs the matching Spanish bit.

Also - this is fantastic documentation. So thorough and clear.

2017-08-24 04:14 UTC, vgayolrs commented
@walshbr , done!

2017-08-24 12:35 UTC, merged