Update sentiment-analysis.md
programminghistorian/jekyll pull request #692
Opened 2018-01-24 19:52 UTC by zoews

Added Acknowledgements section (neglected to copy it over from Part 2!)

2018-01-24 19:57 UTC, ianmilligan1 requested changes

2018-01-24 19:57 UTC, ianmilligan1 commented on lessons/sentiment-analysis.md
> +My sincere thanks to Justin Joque, Visualization Librarian at the University of Michigan Library and the Digital Project Studio for support in formulating the ideas and approach behind this lesson. M
Can you make https://clarkdatalabs.github.io either a clickable link (wrap in `<` and `>`) or maybe even more simply just make the first mention of "Digital Project Studio" a link to the site?

2018-01-24 20:17 UTC, ianmilligan1 approved these changes

2018-01-24 20:17 UTC, ianmilligan1 commented
As @acrymble is editor I'll give him a chance to review and/or merge. Thanks @zoews!

2018-01-25 09:10 UTC, acrymble commented
@zoews can you update the "last modified date" in the header please?

2018-01-25 16:43 UTC, mdlincoln commented
@acrymble That bit of the header is not part of the YAML metadata, but is instead generated by an API call to github. Unfortunately, it seems to be behaving strangely - right now I see `2018-00-22` for this lesson, which is obviously nonsensical. I'm going to merge this first, and then open a new issue about the modified date here because it points to a technical problem that may go beyond this lesson.

2018-01-25 16:43 UTC, merged