Issue #687 - Indian blog post
programminghistorian/jekyll pull request #775
Opened 2018-04-04 09:51 UTC by acrymble

This is the blog post text (very much delayed) from issue #687 regarding Indian audience needs.

2018-04-04 15:13 UTC, mdlincoln requested changes
Add an `authors:` element to the YAML header

2018-04-04 15:34 UTC, acrymble commented
added

2018-04-04 15:36 UTC, mdlincoln approved these changes

2018-04-05 07:52 UTC, drjwbaker approved these changes
:)

2018-04-05 08:39 UTC, merged