Issue 812 - review tickets to YAML
programminghistorian/jekyll pull request #817
Opened 2018-04-27 18:02 UTC by acrymble

As per issue #812, this adds missing 'review-ticket' metadata to 10 English tutorials (not Spanish) for which the data was missing. This should be all English-language cases for which a /submissions page ticket exists.

2018-04-27 18:30 UTC, acrymble commented
Added review-ticket: NULL to all of the really old lessons (pre-open review). And for the 2 that were via pull request only, I just made new tickets, linking to the old pull request.

This should now be all English lessons with the review-ticket field in the YAML.

2018-04-27 19:00 UTC, mdlincoln requested changes
@acrymble for the lessons that were reviewed in pull requests, please just put the full link for those pull requests directly. I'm going to turn all those numbers into full URLs anyway as I noted in #812

2018-04-28 06:05 UTC, acrymble commented
done.

2018-04-28 16:13 UTC, mdlincoln commented
Thanks @acrymble I'm going to merge this into #816

2018-04-28 16:13 UTC, closed without merging