add new translation on linked data
programminghistorian/jekyll pull request #883
Opened 2018-06-02 12:47 UTC by arojascastro

Adding new translation - please approve. Links may be broken? Thanks.

2018-06-02 16:11 UTC, mdlincoln requested changes
After merging that old PR, there's still one broken link reported in this new translation:

```
- ./_site/es/lecciones/introduccion-datos-abiertos-enlazados.html
  *  External link https://es.wikipedia.org/wiki/Serializaci%C3%B3nn failed: 404 No error
```

2018-06-03 07:50 UTC, arojascastro commented
I fixed that link but still the validation is blocked.

2018-06-03 14:34 UTC, mdlincoln commented
@arojascastro yeah, at first glance it does look like one of the checks is failing - but there is a subtle difference between the `/push` Travis test, which is failing, and the `/pr` Travis test, which is passing. The `push` test ONLY looks at _the content of this branch_ - which still includes those bad 404 links that had been caused by other pages. The `pr` test, however, looks at the content of the site that would happen if this pull request were merged into the current branch - and that one passes, because in that test the site now includes those link fixes from when I merged #859.

So the short answer is, the `pr` test shows what will happen once this pull request is merged into the current site - and it is ✅

2018-06-03 14:34 UTC, mdlincoln approved these changes

2018-06-03 14:36 UTC, merged