Adding bio and avatar Sofia Papastamkou, closes #864
programminghistorian/jekyll pull request #890
Opened 2018-06-06 04:54 UTC by spapastamkou

I added my bio to the /data/ph_authors.yml file, and uploaded a square black and white avatar of myself to /avatars). As one of the technical tasks described in #864

2018-06-06 07:33 UTC, acrymble commented
Thanks for doing this @spapastamkou.

Since your bio needs to also appear on the Spanish project team page, you will have to request a translation from someone on our Spanish team (unless you can speak Spanish). You can do that in your pull request by alerting the Spanish team and highlighting that this pull request cannot be accepted until we have a translation. This is as easy as saying @mariajoafana @vgayolrs @arojascastro @jamotilla @jenniferisasi would one of you please translate this?

2018-06-06 07:47 UTC, arojascastro commented
Ok, but shoudn't have a French version first of all?

2018-06-06 08:46 UTC, spapastamkou commented
@acrymble thank you. For the Spanish translation I thought it was enough to pick one of the Spanish-speaking members as reviewer but I'll be more explicite in the future. 
@arojascastro Sure but should we not better wait that a FR edition actually exists before? Or perhaps translate all bios in French could be part of the preparatory work for the FR edition.

2018-06-06 10:46 UTC, acrymble commented
@spapastamkou you will have to do it eventually, so you could translate the snippet into French now if you would like to save time later.

2018-06-06 15:47 UTC, mdlincoln requested changes

2018-06-06 15:47 UTC, mdlincoln commented on _data/ph_authors.yml
> +        Sofia Papastamkou is a historian and Research Engineer in Digital Humanities at the French National Center for Scientific Research (CNRS).
A small change is required: you must indent all lines after `en: |` so that they line up with the `|`

2018-06-06 19:54 UTC, arojascastro approved these changes
spanish translation added. correction by Matthew pending

2018-06-06 20:38 UTC, amsichani approved these changes

2018-06-06 21:23 UTC, mdlincoln commented
Thanks @spapastamkou - now that you've done that, you'll see that "all checks have passed" on this PR which means the site builds successfully.

2018-06-06 21:23 UTC, mdlincoln approved these changes

2018-06-06 21:23 UTC, merged

2018-06-06 22:12 UTC, spapastamkou commented
Thank you!

>

2018-06-07 07:15 UTC, drjwbaker commented
Welcome aboard @spapastamkou! (I always think once someone is on the about page then it is properly official that they are part of the team)

2018-06-07 10:58 UTC, spapastamkou commented
thank you @drjwbaker and all, it is great to be part of THIS team.